// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using SiliconStudio.Core;
using SiliconStudio.Xenko.Shaders;
namespace TilemapTools.Xenko.Rendering
{
    internal static partial class ShaderMixins
    {
        internal partial class TileMeshRenderer  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "TileMeshRendererShader");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TileMeshRenderer", new TileMeshRenderer());
            }
        }
    }
}
